# update-quote.py — fetch a programming quote and rewrite assets/quote.svg
# runs in GitHub Actions every hour. no dependencies. python 3.

import json
import random
import urllib.request
import sys

FALLBACK = {
    "quote": "the best code is written when the world is asleep",
    "author": "kishore"
}

def esc(s):
    return (str(s)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;"))

def wrap(text, max_chars=72, max_lines=3):
    words = text.split()
    lines = []
    cur = ""
    for w in words:
        next_line = (cur + " " + w) if cur else w
        if len(next_line) > max_chars and cur:
            lines.append(cur)
            cur = w
            if len(lines) == max_lines - 1:
                break
        else:
            cur = next_line
    if cur and len(lines) < max_lines:
        lines.append(cur)
    
    consumed = len(" ".join(lines).split())
    if consumed < len(words):
        rest = " ".join(words[consumed:])
        last = lines[max_lines - 1] + " " + rest
        if len(last) > max_chars:
            last = last[:max_chars - 1].rsplit(' ', 1)[0] + "…"
        lines[max_lines - 1] = last
    return lines

def fetch_quote():
    url = "https://raw.githubusercontent.com/mudroljub/programming-quotes-api/master/data/quotes.json"
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "MKishoreDev-README/1.0 (+github actions)",
            "Accept": "application/json"
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as response:
            quotes = json.loads(response.read().decode('utf-8'))
            if isinstance(quotes, list) and len(quotes) > 0:
                j = random.choice(quotes)
                quote = j.get("text", "").strip().lower()
                author = j.get("author", "unknown").strip().lower()
                if quote:
                    return {"quote": quote, "author": author}
            raise ValueError("invalid quote data")
    except Exception as e:
        print(f"quote fetch failed: {e}", file=sys.stderr)
        return FALLBACK

def main():
    data = fetch_quote()
    lines = wrap(data["quote"], 72, 3)
    start_y = 88 if len(lines) == 1 else (78 if len(lines) == 2 else 68)
    line_h = 24
    quote_tspans = "".join(
        f'<tspan x="600" y="{start_y + i * line_h}">{esc(l)}</tspan>'
        for i, l in enumerate(lines)
    )

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 180" width="1200" height="180" role="img" aria-label="developer quote card">
  <title>Developer Quote Card</title>
  <desc>A fresh programming quote, updated hourly by GitHub Actions.</desc>
  <style>@media (prefers-reduced-motion: reduce) {{ * {{ animation: none !important; }} }}</style>
  <!-- quote.svg · regenerated by .github/workflows/update-profile.yml -->
  <defs>
    <linearGradient id="qbg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0c0717"/>
      <stop offset="100%" stop-color="#140b24"/>
    </linearGradient>
    <linearGradient id="qBorder" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%"   stop-color="#432874" stop-opacity="0"/>
      <stop offset="50%"  stop-color="#a78bfa" stop-opacity="0.8"/>
      <stop offset="100%" stop-color="#432874" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="shimmer" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#a78bfa" stop-opacity="0"/>
      <stop offset="50%" stop-color="#a78bfa" stop-opacity="0.07"/>
      <stop offset="100%" stop-color="#a78bfa" stop-opacity="0"/>
    </linearGradient>
  </defs>

  <rect width="1200" height="180" fill="url(#qbg)"/>
  <rect width="1200" height="180" fill="url(#shimmer)" pointer-events="none">
    <animate attributeName="x" values="-1200;1200" dur="4s" repeatCount="indefinite" begin="1.2s"/>
  </rect>
  <rect x="60" y="22" width="1080" height="136" rx="10"
        fill="#0a0612" stroke="#2c1a4d" stroke-width="1.2"/>
  <line x1="60" y1="22"  x2="1140" y2="22"  stroke="url(#qBorder)" stroke-width="1"/>
  <line x1="60" y1="158" x2="1140" y2="158" stroke="url(#qBorder)" stroke-width="1"/>

  <text x="98" y="90" font-family="'Lora',Georgia,serif" font-size="70"
        fill="#432874" opacity="0.8">&#8220;</text>

  <text text-anchor="middle" font-family="'Lora',Georgia,serif"
        font-size="20" font-style="italic" fill="#f5e6d3">
    {quote_tspans}
  </text>
  <text x="600" y="138" text-anchor="middle" font-family="ui-monospace,monospace"
        font-size="11" fill="#8a7a9d" letter-spacing="3">
    ── {esc(data["author"])} ──
  </text>
</svg>
"""
    with open("assets/quote.svg", "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"wrote assets/quote.svg -> {data}")

if __name__ == "__main__":
    main()
