# update-blogs.py — fetch recent blogs and rewrite assets/blog-*.svg & README.md
# runs in GitHub Actions. no dependencies. python 3.

import json
import urllib.request
import sys
import os
import re
from datetime import datetime

FALLBACK_POSTS = [
    {
        "slug": "where-did-everything-go",
        "title": "Where Did Everything Go?",
        "date": "2026-07-12",
        "summary": "A story about my GitHub history, followers, and past Telegram communities.",
        "tags": ["personal", "reflection"],
        "readTime": 9
    },
    {
        "slug": "the-username-that-started-everything",
        "title": "The Username That Started Everything",
        "date": "2026-07-10",
        "summary": "The origin story behind my username and why I eventually decided to leave it.",
        "tags": ["personal", "journey"],
        "readTime": 6
    },
    {
        "slug": "welcome-to-blog",
        "title": "Welcome to the Blog",
        "date": "2026-07-08",
        "summary": "An introduction to why this blog exists and what you will find here.",
        "tags": ["personal", "portfolio"],
        "readTime": 11
    }
]

def esc(s):
    return (str(s)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;"))

def format_date(date_str):
    try:
        months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        d = datetime.strptime(date_str, "%Y-%m-%d")
        return f"{months[d.month - 1]} {d.day}, {d.year}"
    except Exception as e:
        print(f"Date formatting failed: {e}", file=sys.stderr)
        return date_str

def wrap(text, max_chars=28, max_lines=3):
    words = text.split()
    lines = []
    cur = ""
    for w in words:
        next_line = (cur + " " + w) if cur else w
        if len(next_line) > max_chars and cur:
            lines.append(cur)
            cur = w
            if len(lines) == max_lines - 1:
                break
        else:
            cur = next_line
    if cur and len(lines) < max_lines:
        lines.append(cur)
    return lines

def fetch_blogs():
    url = "https://mkishore.is-a.dev/blogs/index.json"
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "MKishoreDev-README/1.0 (+github actions)", "Accept": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as response:
            posts = json.loads(response.read().decode('utf-8'))
            if isinstance(posts, list) and len(posts) > 0:
                return posts[:3]
            raise ValueError("invalid posts JSON")
    except Exception as e:
        print(f"blogs fetch failed: {e}", file=sys.stderr)
        return FALLBACK_POSTS

def read_current_blog_slugs():
    readme_path = "README.md"
    if not os.path.exists(readme_path):
        return []
    with open(readme_path, "r", encoding="utf-8") as f:
        content = f.read()
    start_marker = "<!-- BLOGS:START -->"
    end_marker = "<!-- BLOGS:END -->"
    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)
    if start_idx == -1 or end_idx == -1:
        return []
    section = content[start_idx:end_idx]
    slugs = []
    for match in re.finditer(r'href="https://mkishore\.is-a\.dev/blog/([^"]+)"', section):
        slugs.append(match.group(1))
    return slugs

def render_card(post, index):
    tags = post.get("tags", [])
    tag = f"#{tags[0]}" if tags else "#dev"
    title_lines = wrap(post.get("title", ""), 26, 3)
    
    start_y = 88 if len(title_lines) == 1 else (76 if len(title_lines) == 2 else 64)
    line_h = 22
    title_tspans = "".join(
        f'<tspan x="190" y="{start_y + i * line_h}">{esc(l)}</tspan>'
        for i, l in enumerate(title_lines)
    )
    
    formatted_date = format_date(post.get("date", ""))
    read_time_str = f"{post.get('readTime', 5)} min read"
    
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 380 180" width="380" height="180" role="img" aria-label="blog post card {index + 1}">
  <title>{esc(post.get('title', 'Blog Post'))}</title>
  <desc>Blog card for {esc(post.get('title', ''))}. {esc(post.get('summary', ''))}</desc>
  <style>@media (prefers-reduced-motion: reduce) {{ * {{ animation: none !important; }} }}</style>
  <!-- blog-{index + 1}.svg · generated by .github/workflows/update-profile.yml -->
  <defs>
    <linearGradient id="bbg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0c0717"/>
      <stop offset="100%" stop-color="#140b24"/>
    </linearGradient>
    <linearGradient id="bBorder" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%"   stop-color="#432874" stop-opacity="0"/>
      <stop offset="50%"  stop-color="#a78bfa" stop-opacity="0.8"/>
      <stop offset="100%" stop-color="#432874" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="shimmer" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#a78bfa" stop-opacity="0"/>
      <stop offset="50%" stop-color="#a78bfa" stop-opacity="0.07"/>
      <stop offset="100%" stop-color="#a78bfa" stop-opacity="0"/>
    </linearGradient>
  </defs>

  <rect width="380" height="180" fill="url(#bbg)"/>
  <rect width="380" height="180" fill="url(#shimmer)" pointer-events="none">
    <animate attributeName="x" values="-380;380" dur="3s" repeatCount="indefinite" begin="{1.8 + index * 0.3}s"/>
  </rect>
  <rect x="15" y="15" width="350" height="150" rx="8"
        fill="#0a0612" stroke="#2c1a4d" stroke-width="1.2"/>
  <line x1="15" y1="15"  x2="365" y2="15"  stroke="url(#bBorder)" stroke-width="1"/>
  <line x1="15" y1="165" x2="365" y2="165" stroke="url(#bBorder)" stroke-width="1"/>

  <!-- metadata category -->
  <text x="35" y="42" font-family="ui-monospace,monospace" font-size="10" fill="#a78bfa" letter-spacing="1">
    {esc(tag.lower())}
  </text>
  
  <text x="345" y="42" font-family="ui-monospace,monospace" font-size="10" fill="#8a7a9d" text-anchor="end">
    {esc(formatted_date)}
  </text>

  <!-- title -->
  <text text-anchor="middle" font-family="'Lora',Georgia,serif"
        font-size="16.5" font-weight="600" fill="#f5e6d3">
    {title_tspans}
  </text>

  <!-- footer link hint -->
  <text x="190" y="145" text-anchor="middle" font-family="ui-monospace,monospace"
        font-size="9.5" fill="#8a7a9d" letter-spacing="1">
    read article [{esc(read_time_str)}] ──&gt;
  </text>
</svg>
"""

def update_readme(posts):
    readme_path = "README.md"
    with open(readme_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    start_marker = "<!-- BLOGS:START -->"
    end_marker = "<!-- BLOGS:END -->"
    
    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)
    
    if start_idx == -1 or end_idx == -1:
        print("Could not find BLOGS comment markers in README.md", file=sys.stderr)
        return
        
    table_html = f"""\n<table width="100%" style="border-collapse: collapse; border: none;">
  <tr style="border: none;">
    <td width="33.3%" align="center" style="border: none; padding: 0;">
      <a href="https://mkishore.is-a.dev/blog/{posts[0]['slug']}">
        <img src="./assets/blog-1.svg" alt="{esc(posts[0]['title'])}" width="100%"/>
      </a>
    </td>
    <td width="33.3%" align="center" style="border: none; padding: 0;">
      <a href="https://mkishore.is-a.dev/blog/{posts[1]['slug']}">
        <img src="./assets/blog-2.svg" alt="{esc(posts[1]['title'])}" width="100%"/>
      </a>
    </td>
    <td width="33.3%" align="center" style="border: none; padding: 0;">
      <a href="https://mkishore.is-a.dev/blog/{posts[2]['slug']}">
        <img src="./assets/blog-3.svg" alt="{esc(posts[2]['title'])}" width="100%"/>
      </a>
    </td>
  </tr>
</table>

<div align="center" style="margin-top: 16px;">
  <sub><i>Looking for more? Click <b><a href="https://mkishore.is-a.dev/blogs/">here</a></b> to view all blogs at <b><a href="https://mkishore.is-a.dev/blogs/">mkishore.is-a.dev/blogs</a></b>.</i></sub>
</div>\n"""

    new_content = (
        content[:start_idx + len(start_marker)] +
        table_html +
        content[end_idx:]
    )
    
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print("Updated README.md with latest blog post links")

def main():
    posts = fetch_blogs()
    current_slugs = read_current_blog_slugs()
    new_slugs = [post["slug"] for post in posts]

    if current_slugs == new_slugs:
        print("No new blogs, skipping update")
        return

    for i, post in enumerate(posts):
        card_svg = render_card(post, i)
        with open(f"assets/blog-{i + 1}.svg", "w", encoding="utf-8") as f:
            f.write(card_svg)
        print(f"wrote assets/blog-{i + 1}.svg -> {post['title']}")

    update_readme(posts)

if __name__ == "__main__":
    main()
